services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=yelp-cluster
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: yelp-jupyter
    depends_on:
      - namenode
      - datanode
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  hadoop_namenode:
  hadoop_datanode: